project_id = "swxtrurrgjuhyvqbmdvc"

[functions.generate-art-image]
verify_jwt = false

[functions.extract-brands]
verify_jwt = false

[functions.sync-to-shopify]
verify_jwt = false

[functions.remove-background]
verify_jwt = false
