project_id = "swxtrurrgjuhyvqbmdvc"

[functions.generate-art-image]
verify_jwt = false

[functions.extract-brands]
verify_jwt = false

[functions.sync-to-shopify]
verify_jwt = false

[functions.remove-background]
verify_jwt = false

[functions.firecrawl-search]
verify_jwt = false

[functions.authenticate-item]
verify_jwt = false

[functions.check-removebg-usage]
verify_jwt = false

[functions.ai-background-replace]
verify_jwt = false
